/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssistantAvatar: typeof import('./components/chat/AssistantAvatar.vue')['default']
    AttachmentsMessage: typeof import('./components/chat/AttachmentsMessage.vue')['default']
    ChatComposer: typeof import('./components/chat/ChatComposer.vue')['default']
    ChatHeader: typeof import('./components/ChatHeader.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilePreviewPanel: typeof import('./components/FilePreviewPanel.vue')['default']
    LeftPanel: typeof import('./components/LeftPanel.vue')['default']
    MarkdownContent: typeof import('./components/MarkdownContent.vue')['default']
    MessageActions: typeof import('./components/chat/MessageActions.vue')['default']
    PlanPanel: typeof import('./components/chat/PlanPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionDetailView: typeof import('./components/SessionDetailView.vue')['default']
    SessionHeader: typeof import('./components/SessionHeader.vue')['default']
    SessionList: typeof import('./components/SessionList.vue')['default']
    SessionListItem: typeof import('./components/SessionListItem.vue')['default']
    SettingsButton: typeof import('./components/SettingsButton.vue')['default']
    SettingsModal: typeof import('./components/SettingsModal.vue')['default']
    SuggestedQuestions: typeof import('./components/SuggestedQuestions.vue')['default']
    ThinkingBlock: typeof import('./components/chat/ThinkingBlock.vue')['default']
    ThinkingIndicator: typeof import('./components/chat/ThinkingIndicator.vue')['default']
    ToolCallCard: typeof import('./components/chat/ToolCallCard.vue')['default']
    ToolPreviewPanel: typeof import('./components/chat/ToolPreviewPanel.vue')['default']
    VNCOverlay: typeof import('./components/VNCOverlay.vue')['default']
    VNCViewer: typeof import('./components/VNCViewer.vue')['default']
  }
}
