server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name llmops.shortvar.com;
    resolver 127.0.0.11 valid=30s ipv6=off;

    location /api/ {
        set $llmops_api http://llmops-api:5001;
        proxy_pass $llmops_api;
        rewrite ^/api/(.*)$ /$1 break;
        include proxy.conf;
    }

    location / {
        set $llmops_ui http://llmops-ui:3000;
        proxy_pass $llmops_ui;
        include proxy.conf;
    }

    ssl_certificate ./../ssl/llmops.shortvar.com.crt;
    ssl_certificate_key ./../ssl/llmops.shortvar.com.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
}
