import type { App, Component, SetupContext } from 'vue'
import { h } from 'vue'
import { ElIcon } from 'element-plus'
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Calendar,
  CaretBottom,
  ChatDotSquare,
  ChatLineRound,
  ChatRound,
  Check,
  CircleCheckFilled,
  CirclePlusFilled,
  Close,
  Compass,
  CopyDocument,
  Collection,
  CollectionTag,
  DataBoard,
  Delete,
  Document,
  DocumentChecked,
  DocumentCopy,
  Edit,
  Filter,
  FolderOpened,
  Grid,
  HomeFilled,
  InfoFilled,
  Link,
  List,
  Loading,
  Lock,
  MagicStick,
  Menu,
  Microphone,
  Minus,
  Monitor,
  More,
  Operation,
  Picture,
  Plus,
  Promotion,
  QuestionFilled,
  Rank,
  Refresh,
  Remove,
  Setting,
  SwitchButton,
  Tickets,
  Tools,
  User,
  VideoPause,
  VideoPlay,
  Warning,
  WarningFilled,
} from '@element-plus/icons-vue'
import IconGithub from '@/components/icons/IconGithub.vue'

function registerEpIcon(
  app: App,
  name: string,
  IconComp: Component,
  options?: { loadingSpin?: boolean },
) {
  app.component(name, {
    props: { size: [Number, String] },
    setup(props: { size?: number | string }, { attrs }: SetupContext) {
      return () =>
        h(
          ElIcon,
          {
            size: props.size !== undefined && props.size !== '' ? Number(props.size) : undefined,
            class: options?.loadingSpin ? 'is-loading' : undefined,
            ...attrs,
          },
          () => h(IconComp),
        )
    },
  })
}

/** 将原 Arco 图标名注册为 Element Plus 图标，模板里仍可使用 `<icon-xxx />` */
export function registerAppIcons(app: App) {
  const pairs: [string, Component, { loadingSpin?: boolean }?][] = [
    ['IconApps', Grid],
    ['IconCheck', Check],
    ['IconLoading', Loading, { loadingSpin: true }],
    ['IconPause', VideoPause],
    ['IconPlayCircle', VideoPlay],
    ['IconList', List],
    ['IconUp', ArrowUp],
    ['IconDown', ArrowDown],
    ['IconRight', ArrowRight],
    ['IconFile', Document],
    ['IconLanguage', ChatLineRound],
    ['IconStorage', FolderOpened],
    ['IconTool', Tools],
    ['IconMessage', ChatDotSquare],
    ['IconQuestionCircle', QuestionFilled],
    ['IconSync', Refresh],
    ['IconUser', User],
    ['IconLock', Lock],
    ['IconGithub', IconGithub],
    ['IconEdit', Edit],
    ['IconMore', More],
    ['IconEmpty', Picture],
    ['IconPoweroff', SwitchButton],
    ['IconClose', Close],
    ['IconPlus', Plus],
    ['IconVoice', Microphone],
    ['IconSend', Promotion],
    ['IconCommon', Menu],
    ['IconSettings', Setting],
    ['IconCopy', CopyDocument],
    ['IconDashboard', DataBoard],
    ['IconComputer', Monitor],
    ['IconBulb', MagicStick],
    ['IconCode', Tickets],
    ['IconQuestionCircleFill', QuestionFilled],
    ['IconLeft', ArrowLeft],
    ['IconSchedule', Calendar],
    ['IconCheckCircleFill', CircleCheckFilled],
    ['IconMinusCircle', Remove],
    ['IconCompass', Compass],
    ['IconWechat', ChatRound],
    ['IconPlayArrow', VideoPlay],
    ['IconPlusCircleFill', CirclePlusFilled],
    ['IconHome', HomeFilled],
    ['IconBranch', Rank],
    ['IconLink', Link],
    ['IconFilter', Filter],
    ['IconDelete', Delete],
    ['IconExclamationCircleFill', WarningFilled],
    ['IconExclamationCircle', Warning],
    ['IconPaste', DocumentCopy],
    ['IconCaretDown', CaretBottom],
    ['IconPushpin', CollectionTag],
    ['IconBookmark', Collection],
    ['IconSave', DocumentChecked],
    ['IconTranslate', Operation],
    ['IconInfoCircle', InfoFilled],
    ['IconObliqueLine', Minus],
  ]

  for (const [name, comp, opts] of pairs) {
    registerEpIcon(app, name, comp, opts)
  }
}
